<a href="https://colab.research.google.com/github/Sheraz55/Deep-learning-assignments/blob/main/Ionosphere_Data_Problem.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from numpy import nan as NA
import matplotlib.pylab as plt

In [ ]:
dataset = pd.read_csv('/content/ionosphere_data.csv')
dataset.head()

feature1  feature2  feature3  ...  feature33  feature34  label
0         1         0   0.99539  ...    0.18641   -0.45300      g
1         1         0   1.00000  ...   -0.13738   -0.02447      b
2         1         0   1.00000  ...    0.56045   -0.38238      g
3         1         0   1.00000  ...   -0.32382    1.00000      b
4         1         0   1.00000  ...   -0.04608   -0.65697      g

[5 rows x 35 columns]

In [ ]:
dataset.isnull().values.any()

False

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 351 entries, 0 to 350
Data columns (total 35 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   feature1   351 non-null    int64  
 1   feature2   351 non-null    int64  
 2   feature3   351 non-null    float64
 3   feature4   351 non-null    float64
 4   feature5   351 non-null    float64
 5   feature6   351 non-null    float64
 6   feature7   351 non-null    float64
 7   feature8   351 non-null    float64
 8   feature9   351 non-null    float64
 9   feature10  351 non-null    float64
 10  feature11  351 non-null    float64
 11  feature12  351 non-null    float64
 12  feature13  351 non-null    float64
 13  feature14  351 non-null    float64
 14  feature15  351 non-null    float64
 15  feature16  351 non-null    float64
 16  feature17  351 non-null    float64
 17  feature18  351 non-null    float64
 18  feature19  351 non-null    float64
 19  feature20  351 non-null    float64
 20  feature21 

In [ ]:
dataset.describe()

feature1  feature2    feature3  ...   feature32   feature33   feature34
count  351.000000     351.0  351.000000  ...  351.000000  351.000000  351.000000
mean     0.891738       0.0    0.641342  ...   -0.003794    0.349364    0.014480
std      0.311155       0.0    0.497708  ...    0.513574    0.522663    0.468337
min      0.000000       0.0   -1.000000  ...   -1.000000   -1.000000   -1.000000
25%      1.000000       0.0    0.472135  ...   -0.242595    0.000000   -0.165350
50%      1.000000       0.0    0.871110  ...    0.000000    0.409560    0.000000
75%      1.000000       0.0    1.000000  ...    0.200120    0.813765    0.171660
max      1.000000       0.0    1.000000  ...    1.000000    1.000000    1.000000

[8 rows x 34 columns]

In [ ]:
dataset.shape

(351, 35)

**Splitting data into 60:40**

In [ ]:
train_data = dataset.iloc[0:210, 0:-1]
train_targets = dataset.iloc[0:210, -1]

test_data = dataset.iloc[210:, 0:-1]
test_targets = dataset.iloc[210:, -1]

print(train_data.shape)
print(train_targets.shape)
print(test_data.shape)
print(test_targets.shape)

(210, 34)
(210,)
(141, 34)
(141,)


In [ ]:
# split into input (X) and output (Y) variables
from sklearn.preprocessing import LabelEncoder
X = dataset.values[1:,0:34].astype(float)
Y = dataset.values[1:,34]
# encode class values as integers
encoder = LabelEncoder()
encoder.fit(Y)
Y = encoder.transform(Y)
print(X)
print(Y)

[[ 1.       0.       1.      ... -0.06288 -0.13738 -0.02447]
 [ 1.       0.       1.      ... -0.2418   0.56045 -0.38238]
 [ 1.       0.       1.      ...  1.      -0.32382  1.     ]
 ...
 [ 1.       0.       0.94701 ...  0.00442  0.92697 -0.00577]
 [ 1.       0.       0.90608 ... -0.03757  0.87403 -0.16243]
 [ 1.       0.       0.8471  ... -0.06678  0.85764 -0.06151]]
[0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0
 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0
 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0
 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1

**Modeling**

In [ ]:
from keras import models
from keras import layers

model = models.Sequential()
model.add(layers.Dense(16, activation='relu', input_dim = 34))
model.add(layers.Dense(1, activation='sigmoid'))

**Compilation**

In [ ]:
model.compile(optimizer='rmsprop',
              loss = 'binary_crossentropy',
              metrics = ['accuracy'])

**Training**

In [ ]:
model.fit(X, Y, epochs=100, batch_size=5)

Epoch 1/100
70/70 [==============================] - 0s 2ms/step - loss: 0.5738 - accuracy: 0.7114
Epoch 2/100
70/70 [==============================] - 0s 2ms/step - loss: 0.5079 - accuracy: 0.7314
Epoch 3/100
70/70 [==============================] - 0s 2ms/step - loss: 0.4633 - accuracy: 0.7829
Epoch 4/100
70/70 [==============================] - 0s 2ms/step - loss: 0.4243 - accuracy: 0.8371
Epoch 5/100
70/70 [==============================] - 0s 2ms/step - loss: 0.3902 - accuracy: 0.8714
Epoch 6/100
70/70 [==============================] - 0s 2ms/step - loss: 0.3596 - accuracy: 0.8943
Epoch 7/100
70/70 [==============================] - 0s 2ms/step - loss: 0.3301 - accuracy: 0.9029
Epoch 8/100
70/70 [==============================] - 0s 2ms/step - loss: 0.3035 - accuracy: 0.9000
Epoch 9/100
70/70 [==============================] - 0s 2ms/step - loss: 0.2817 - accuracy: 0.9171
Epoch 10/100
70/70 [==============================] - 0s 2ms/step - loss: 0.2625 - accuracy: 0.9200
Epoch 11/

**Evaluation**

In [ ]:
model.evaluate(X,Y)

11/11 [==============================] - 0s 2ms/step - loss: 0.0394 - accuracy: 0.9857


[0.03936360776424408, 0.9857142567634583]

**Prediction**

In [ ]:
model.predict(X)

array([[3.38368416e-02],
       [9.99207735e-01],
       [4.82419133e-03],
       [9.82805967e-01],
       [5.31798601e-03],
       [9.85811889e-01],
       [4.16815281e-04],
       [9.97790575e-01],
       [1.25008821e-03],
       [9.95042205e-01],
       [6.31076097e-03],
       [9.98603582e-01],
       [1.92158222e-02],
       [9.95828331e-01],
       [2.07909942e-03],
       [9.98503864e-01],
       [1.00084037e-06],
       [9.78810549e-01],
       [4.43388956e-07],
       [9.97999549e-01],
       [1.25844013e-09],
       [9.97977912e-01],
       [1.92180299e-10],
       [9.99340534e-01],
       [2.15027034e-02],
       [9.92844701e-01],
       [6.29002625e-06],
       [9.99098599e-01],
       [5.73153011e-05],
       [9.97733831e-01],
       [1.54602390e-07],
       [9.95637536e-01],
       [1.02953315e-02],
       [9.82092381e-01],
       [7.09697415e-05],
       [9.98988748e-01],
       [1.87631888e-09],
       [9.98540044e-01],
       [1.15610600e-01],
       [9.96261358e-01],
